development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:7a791272da958f26c8883ad2d73a653d@spinyfin.redistogo.com:10781/
  channel_prefix: notification_production
